### ISSUE TITLE
Back faces of transform cards are all missing

### ISSUE THREAD

**Issue by Cheldra** [Cockatrice/Magic-Spoiler#148]
I think scryfall's changed the way they display transform cards (e.g. see https://scryfall.com/search?q=%2B%2Be%3Axln+o%3Atransform), which is probably the cause.

**Comment by tooomm** [comment]
We aren't checking scryfall for Ixalan I guess. Default is always mtgs, and there is no scryfallOnly or mythicOnly set on Ixalan in set_info.

But you are right ([reddit realized it too](https://www.reddit.com/r/Cockatrice/comments/6wkroe/xlnxml/dmvjgs0/)), for all DFC there are just the front sides included. 🙈 
They are correctly related in the created [`XLN.xml`](https://github.com/Cockatrice/Magic-Spoiler/blob/files/XLN.xml#L58) file, but no back side card name, rules text or pictures are included.
But the [`XLN.json`](https://github.com/Cockatrice/Magic-Spoiler/blob/b9f2992e1daa0a4c6f12cb2c41cef11cde2b5230/XLN.json#L159) is all corret!

So this is a xml only problem, more particular for the `set.xml` output.
That's why a reddit user complained. the xml file for the set only file is listed there. With the general spoiler xml linked he would have seen the back sides, but with additional text attached in the rules field.

Examples:
"Legion's Landing" --> no "Adanto, the First Fort" in xln.xml, but in xln.json
"Treasure Map" --> no "Treasure Cove" in xln.xml, but in xln.json

Additionally there is a different issue with the spoiler.xml/json files:
- `spoiler.xml`: https://github.com/Cockatrice/Magic-Spoiler/blob/b9f2992e1daa0a4c6f12cb2c41cef11cde2b5230/spoiler.xml#L103
There is a unusual new line, same for its back side.
So spoiler.xml has back sides, while xln.xml hasn't.
But spoiler.xml has this new `(Related: Legion's Landing)` addition at the end of the rules text.

- [`spoiler.json`](https://github.com/Cockatrice/Magic-Spoiler/blob/b9f2992e1daa0a4c6f12cb2c41cef11cde2b5230/spoiler.json) is all good


It looks like the issue is about correctly transforming data from json over to xml, as well as creating our xml files, especially since there are differences between xln.xml and spoiler.xml.

**Comment by Cheldra** [comment]
Solved #173
