### ISSUE TITLE
Toggle SpoilerSeasonStatus (create/delete SpoilerSeasonEnabled file)

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Magic-Spoiler#195]
Determine if any spoilers exist (and not in mtgjson) and toggle SpoilerSeasonStatus in files branch

**Comment by ZeldaZach** [comment]
Should be between "enabled" and "disabled"

**Comment by tooomm** [comment]
With https://github.com/Cockatrice/Cockatrice/pull/2991 the final behavior changed:
>On Cockatrice launch, **check if the file "SpoilerSeasonEnabled" exists on the Magic-Spoiler repo**. If it does not, then we know we are not in spoiler season and will continue with normal launch.

The content doesn't matter any more, only the `SpoilerSeasonEnabled` file is checked for existence instead.

Any automation regarding this is highly appreciated and should be done in conjunction with https://github.com/Cockatrice/Magic-Spoiler/issues/126.

**Comment by tooomm** [comment]
This should be done in script by Travis automatically!

Otherwise people run into problems like recently when M19 is found in MTGJSON and dropped from spoilers, but since the spoiler season file is still there, Cockatrice things season is running and replaces the full spoiler file with an empty one. Just the general spoilers updated hint is shown and people are left with no single new card and no clue, since only the spoiler season ended notification shows the hint to run Oracle.

Once Travis detects that an enabled spoiler set is already available in MTGJSON - and it's the only set left in spoiler.xml - Travis should remove the SpoilerSeasonEnabled file alltogether to trigger the helpful hint on how to get the cards again when transition from spoilers to regular cards.

The other way around with new spoilers:
If the first cards are added to an empty spoiler.xml file, Travis should enable the spoiler season again (create SpoilerSeasonEnabled file).
