### ISSUE TITLE
Script runs into UnicodeEncodeError

### ISSUE THREAD

**Issue by jipege** [Cockatrice/Magic-Spoiler#253]
Found a problem at Scryfall side, M21 release date was set wrong (possible problem why it couldn't get into spoiler category), got it fixed. Trying to run prog on my own PC right now, run into unicode trouble.
2XM gets handled fine, but somewhere at M21 handling I get this UnicodeEncodeError.
Not sure if its problem on my side, on Scryfall or on yours, but I think it might be mentioned.
![Annotation 2020-06-12 222326](https://user-images.githubusercontent.com/42038728/84539025-620cdb80-acfb-11ea-94c0-9d212b11f15b.png)

**Comment by tooomm** [comment]
Hi @jipege. Sorry that nobody came back to you for that long.
Actually I think the automatic spoiler updater running the code from this repo did work fine for M21... but it's a while since. :)
I'm cleaning up the repo from old & outdated stuff and stumbled upon your post from last year accidentally...

In case you didn't find the solution in between 🙈, I've good news for you 😄 
I ran into the same issue and found the solution for myself a few weeks ago. I assume you're also running on Windows?

You need to make sure that the correct encoding is set (UTF-8), which you are required to do manually on Windows when running the script:

```
$> python -X utf8 -m magic_spoiler
```

<br>

~~I even requested to add a note to the readme for other people (like you) running the script manually on Windows: https://github.com/Cockatrice/Magic-Spoiler/pull/267~~

**Update:** The linked PR now makes some change to the script directly to require UTF-8. That way Windows users can use the script the same way and don't need to manually adjust the mode the script runs in. 👍
