### ISSUE TITLE
Question about re-adding image url appendix

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#290]
@ebbit1q I saw your recently pushed change directly to master (https://github.com/Cockatrice/Magic-Spoiler/commit/c4764f3c17788cda05b8e1e0f2db894ffb9eade8).
I'm not so sure if that's useful... can you give some details why we want to not discard those extensions?

Keeping them, also comes with a downside for us... hence I'm wondering why we want to maintain such noise.
We get now updates to the spoiler files that only change the appended key at the end of the pictures sometimes:
https://github.com/Cockatrice/Magic-Spoiler/commit/9b2948538fb5912f1dfbbb973b8287d8746c36eb#diff-8fdca709787e318dec9624b15c11c231a392ad9be74431871f273885b83ce715
Considering #129 is fixed, those would trigger new updates without actual new data available and notify people falsely.

But all urls still point to the same image, no matter their key - or using no key at all (recent example: [Tamiyo, Compleated Sage](https://scryfall.com/card/neo/238/tamiyo-compleated-sage))
https://c1.scryfall.com/file/scryfall-cards/normal/front/c/e/ce16028f-25d0-4817-b20e-8b390b80ef35.jpg?1644530205 (old url)
https://c1.scryfall.com/file/scryfall-cards/normal/front/c/e/ce16028f-25d0-4817-b20e-8b390b80ef35.jpg?1644710080 (new url)
https://c1.scryfall.com/file/scryfall-cards/normal/front/c/e/ce16028f-25d0-4817-b20e-8b390b80ef35.jpg (clean url)

Another example shortly after is https://github.com/Cockatrice/Magic-Spoiler/commit/8606b7b6cd8e15631f4c2b28d751e02fa09ee455#diff-68636c90d4e07b84ef76367c2652e2022f3d9f288b050cb3add6ffb9d7ee63bd

**Comment by ebbit1q** [comment]
the use of this suffix is to force scryfall's cdn to use the new image, the cdn has geolocated cache servers that will handle requests quicker but will not update immediately when an image is changed, at which point you'd get a different image from those two urls, so when this suffix changes it means the image has gotten a better scan, I see no reason not to update the xml accordingly in order to remove this chance of getting the old scan from a cache server
