### ISSUE TITLE
Run XML through Cockatrice's XSD

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Magic-Spoiler#50]
Cockatrice provides an XSD file that can be used to verify the integrity of an XML file in conforming to the card database standard.  The spoiler XMLs should be verified against it on every update.

https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/cards.xsd

**Comment by tooomm** [comment]
The Cockatrice xsd file seems to need an update first:
https://github.com/Cockatrice/Cockatrice/issues/2065
https://github.com/Cockatrice/Cockatrice/issues/1207


Edit: https://github.com/Cockatrice/Cockatrice/pull/2781 done! Thanks @psithief

**Comment by leematos** [comment]
Hey hey! Was gonna build this app, glad it exists. Would rather contribute than duplicate effort. :) For the XSD, how were you thinking, in python or can travis access xmlint?

**Comment by dev-id** [comment]
Travis can run xmllint, haven't looked for a python package that handles xsd verification.

**Comment by tooomm** [comment]
The one we already use should be fine, no? --> lxml
http://lxml.de/3.0/validation.html

**Comment by dev-id** [comment]
Just found that myself, yes we already use lxml (it's most of our travis time installing it!)

**Comment by tooomm** [comment]
So we should find a smaller/quicker alternative and replace it completely! :D

**Comment by leematos** [comment]
I'm not too familiar with Travis, but you could probably pre-compile it or some such to avoid installing it every time. I come from GitLab CI which lets you use any docker image to do CI things, so I expect travis to let us do speed up things too :)

**Comment by tooomm** [comment]
There is a lot of potential to speed travis up for sure!

Right now we use a quick and dirty way to make it work with the normal python script.
We just did very few travis-related changes/optimizations so far. So there is a lot of room for improvement. I actually read about some things regarding that today...
Travis also supports docker images btw: https://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/

**Comment by tooomm** [comment]
On [travis_speedup](https://github.com/Cockatrice/Magic-Spoiler/tree/tooomm-travis_speedup) branch we are now down to ~2min 40s. 👍 
Used the -O0 cflag as suggested for ci environments: http://lxml.de/installation.html

Wheels are not possible: https://github.com/travis-ci/travis-ci/issues/1531#issuecomment-70855128

Caching seems to not help because the downloads of the packages are very small and we still need to build them - it even adds ~10s: https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone
*(with the new trusty build infrastructure it's pretty sweet though and working great)*

>Found some other option which gets us as low as ~1min 50s with a `--download-cache` addition to the install requirements (+enabled pip cache)
>https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/249486563
>
> Seemed to be a lucky CI shot, went up for concurrent builds --> Travis variance regarding time maybe
> Download-cache command is also not supported in newer pip versions I guess

Another option is to use addons to install apt packages:
https://github.com/akretion/account-financial-reporting/commit/5a48b9dedc43a41248cf3d14a66ddf950d6dc2b5 (we are using container based already)
(I assume here lxml = python-lxml. python-lxml is [whitelisted](https://github.com/travis-ci/apt-package-whitelist/pull/2343) in travis)
It works quickly: https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/249490093#L139-L159
But not sure which other changes are needed as well. Right now normal lxml is installed from requirements.txt additionally.

Also found this, for real binary caching: https://github.com/paylogic/pip-accel

Regarding the docker build: https://hub.docker.com/r/frolvlad/alpine-python2/
